use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fs;
use std::path::PathBuf;

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PaletteCache {
    pub colors: Vec<String>,
    pub source: String,
}

// ~/.cache/oxide/<hash>/
fn cache_dir() -> PathBuf {
    let base = dirs::cache_dir().unwrap_or_else(|| PathBuf::from("/tmp"));
    base.join("oxide")
}

fn cache_key(image_path: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(image_path.as_bytes());
    format!("{:x}", hasher.finalize())
}

fn ensure_cache_dir() {
    fs::create_dir_all(cache_dir()).ok();
}

/// Load cached palette for an image (returns None if not cached).
pub fn load(image_path: &str) -> Option<PaletteCache> {
    let path = cache_dir().join(cache_key(image_path)).join("palette.toml");
    if !path.exists() {
        return None;
    }
    let content = fs::read_to_string(&path).ok()?;
    toml::from_str(&content).ok()
}

/// Save palette to cache and write all export files.
/// `colors` is the full extracted palette (any length).
/// The CSS output is generated dynamically from however many colors are passed.
pub fn save(image_path: &str, colors: &[String]) {
    ensure_cache_dir();

    let dir = cache_dir().join(cache_key(image_path));
    fs::create_dir_all(&dir).ok();

    // --- palette.toml (raw cache record) ---
    let cache = PaletteCache {
        colors: colors.to_vec(),
        source: image_path.to_string(),
    };
    let content = toml::to_string(&cache).unwrap();
    fs::write(dir.join("palette.toml"), content).ok();

    // Derive bg (darkest) and fg (lightest/mid) the same way pywal does:
    // color0 = background, color<mid> = foreground
    let bg = colors.first().map(String::as_str).unwrap_or("#000000");
    let fg = colors
        .get(colors.len() / 2)
        .map(String::as_str)
        .unwrap_or("#ffffff");

    write_colors_css(image_path, colors, bg, fg, &dir);

    println!("[i] cache: Saved {} colors to {:?}", colors.len(), dir);
}

/// Generate CSS custom-properties file — dynamic number of colors,
/// mirrors pywal's colors.css exactly.
fn write_colors_css(source: &str, palette: &[String], bg: &str, fg: &str, dir: &PathBuf) {
    let mut color_vars = String::new();
    for (i, color) in palette.iter().enumerate() {
        color_vars.push_str(&format!("    --color{i}: {color};\n"));
    }

    let css = format!(
        r#"/* CSS variables
   Generated by oxide */
:root {{
    --wallpaper: url("{source}");

    /* Special */
    --background: {bg};
    --foreground: {fg};
    --cursor: {fg};

    /* Colors */
{color_vars}}}"#
    );

    fs::write(dir.join("colors.css"), css).ok();
}

/// Delete cached data for an image (used by --reload).
pub fn invalidate(image_path: &str) {
    let dir = cache_dir().join(cache_key(image_path));
    fs::remove_dir_all(&dir).ok();
}

/// Return the cache directory for a given image path.
pub fn get_cache_dir(image_path: &str) -> PathBuf {
    cache_dir().join(cache_key(image_path))
}
