use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fs;
use std::path::PathBuf;

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PaletteCache {
    pub colors: Vec<String>,
    pub source: String,
}

fn cache_dir() -> PathBuf {
    let base = dirs::cache_dir().unwrap_or_else(|| PathBuf::from("/tmp"));
    base.join("oxide")
}

fn cache_key(image_path: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(image_path.as_bytes());
    format!("{:x}", hasher.finalize())
}

fn ensure_cache_dir() {
    fs::create_dir_all(cache_dir()).ok();
}

pub fn load(image_path: &str) -> Option<PaletteCache> {
    let path = cache_dir().join(cache_key(image_path)).join("palette.toml");
    if !path.exists() {
        return None;
    }
    let content = fs::read_to_string(&path).ok()?;
    toml::from_str(&content).ok()
}

pub fn save(image_path: &str, colors: &[String]) {
    ensure_cache_dir();

    let dir = cache_dir().join(cache_key(image_path));
    fs::create_dir_all(&dir).ok();

    let cache = PaletteCache {
        colors: colors.to_vec(),
        source: image_path.to_string(),
    };
    let content = toml::to_string(&cache).unwrap();
    fs::write(dir.join("palette.toml"), content).ok();

    let bg = colors.first().map(String::as_str).unwrap_or("#000000");
    let fg = colors
        .get(colors.len() / 2)
        .map(String::as_str)
        .unwrap_or("#ffffff");

    write_colors_css(image_path, colors, bg, fg, &dir);
    write_colors_scss(colors, bg, fg, &dir);
    write_colors_json(colors, &dir);
    write_colors_shell(colors, &dir);

    println!("[i] cache: Saved {} colors to {:?}", colors.len(), dir);
}

fn write_colors_css(source: &str, palette: &[String], bg: &str, fg: &str, dir: &PathBuf) {
    let mut color_vars = String::new();
    for (i, color) in palette.iter().enumerate() {
        color_vars.push_str(&format!("    --color{}: {};\n", i, color));
    }

    let css = format!(
        "/* CSS variables\n   Generated by oxide */\n:root {{\n    --wallpaper: url(\"{}\");\n\n    /* Special */\n    --background: {};\n    --foreground: {};\n    --cursor: {};\n\n    /* Colors */\n{}}}",
        source, bg, fg, fg, color_vars
    );

    fs::write(dir.join("colors.css"), css).ok();
}

fn write_colors_scss(palette: &[String], bg: &str, fg: &str, dir: &PathBuf) {
    let mut scss = String::new();
    scss.push_str("/* SCSS variables\n   Generated by oxide */\n");
    scss.push_str(&format!(
        "$wallpaper: url(\"{}\");\n\n",
        dir.file_name()
            .map(|s| s.to_string_lossy())
            .unwrap_or_default()
    ));
    scss.push_str("/* Special */\n");
    scss.push_str(&format!("$background: {};\n", bg));
    scss.push_str(&format!("$foreground: {};\n", fg));
    scss.push_str(&format!("$cursor: {};\n\n", fg));
    scss.push_str("/* Colors */\n");
    for (i, color) in palette.iter().enumerate() {
        scss.push_str(&format!("$color{}: {};\n", i, color));
    }

    fs::write(dir.join("colors.scss"), scss).ok();
}

fn write_colors_json(palette: &[String], dir: &PathBuf) {
    let json = serde_json::to_string_pretty(&palette).unwrap();
    fs::write(dir.join("colors.json"), json).ok();
}

fn write_colors_shell(palette: &[String], dir: &PathBuf) {
    let mut sh = String::new();
    for (i, color) in palette.iter().enumerate() {
        sh.push_str(&format!("color{}=\"{}\"\n", i, color));
    }
    fs::write(dir.join("colors.sh"), sh).ok();
}

pub fn invalidate(image_path: &str) {
    let dir = cache_dir().join(cache_key(image_path));
    fs::remove_dir_all(&dir).ok();
}

pub fn get_cache_dir(image_path: &str) -> PathBuf {
    cache_dir().join(cache_key(image_path))
}
