use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fs;
use std::path::PathBuf;

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PaletteCache {
    pub colors: Vec<String>,
    pub source: String,
}

fn cache_dir() -> PathBuf {
    let base = dirs::cache_dir().unwrap_or_else(|| PathBuf::from("/tmp"));
    base.join("oxide")
}

fn cache_key(image_path: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(image_path.as_bytes());
    format!("{:x}", hasher.finalize())
}

fn ensure_cache_dir() {
    fs::create_dir_all(cache_dir()).ok();
}

pub fn load(image_path: &str) -> Option<PaletteCache> {
    let base = cache_dir();
    let key = cache_key(image_path);
    let path = base.join(&key).join("palette.toml");
    if !path.exists() {
        return None;
    }
    let content = fs::read_to_string(&path).ok()?;
    toml::from_str(&content).ok()
}

pub fn save(image_path: &str, colors: &[String]) {
    ensure_cache_dir();

    let base = cache_dir();
    let key = cache_key(image_path);
    let dir = base.join(key);
    fs::create_dir_all(&dir).ok();

    let toml_path = dir.join("palette.toml");
    let cache = PaletteCache {
        colors: colors.to_vec(),
        source: image_path.to_string(),
    };
    let content = toml::to_string(&cache).unwrap();
    fs::write(&toml_path, content).ok();

    let palette = ensure_16_colors(colors);
    let bg = &palette[0];
    let fg = &palette[7];

    fs::write(dir.join("colors"), palette.join("\n")).ok();
    write_colors_json(image_path, &palette, bg, fg, &dir);
    write_colors_sh(image_path, &palette, bg, fg, &dir);
    write_colors_css(image_path, &palette, bg, fg, &dir);
    write_colors_scss(image_path, &palette, bg, fg, &dir);
}

fn ensure_16_colors(colors: &[String]) -> Vec<String> {
    if colors.len() >= 16 {
        return colors[..16].to_vec();
    }

    let mut palette = colors.to_vec();
    palette.resize(
        16,
        colors
            .last()
            .cloned()
            .unwrap_or_else(|| "#000000".to_string()),
    );
    palette
}

fn write_colors_json(source: &str, palette: &[String], bg: &str, fg: &str, dir: &PathBuf) {
    let json = format!(
        r#"{{
    "wallpaper": "{}",
    "alpha": "100",

    "special": {{
        "background": "{}",
        "foreground": "{}",
        "cursor": "{}"
    }},
    "colors": {{
        "color0": "{}",
        "color1": "{}",
        "color2": "{}",
        "color3": "{}",
        "color4": "{}",
        "color5": "{}",
        "color6": "{}",
        "color7": "{}",
        "color8": "{}",
        "color9": "{}",
        "color10": "{}",
        "color11": "{}",
        "color12": "{}",
        "color13": "{}",
        "color14": "{}",
        "color15": "{}"
    }}
}}"#,
        source,
        bg,
        fg,
        fg,
        palette[0],
        palette[1],
        palette[2],
        palette[3],
        palette[4],
        palette[5],
        palette[6],
        palette[7],
        palette[8],
        palette[9],
        palette[10],
        palette[11],
        palette[12],
        palette[13],
        palette[14],
        palette[15]
    );
    fs::write(dir.join("colors.json"), json).ok();
}

fn write_colors_sh(source: &str, palette: &[String], bg: &str, fg: &str, dir: &PathBuf) {
    let sh = format!(
        r##"# Shell variables
# Generated by 'wal'
wallpaper='{}'

# Special
background='{}'
foreground='{}'
cursor='{}'

# Colors
color0='{}'
color1='{}'
color2='{}'
color3='{}'
color4='{}'
color5='{}'
color6='{}'
color7='{}'
color8='{}'
color9='{}'
color10='{}'
color11='{}'
color12='{}'
color13='{}'
color14='{}'
color15='{}'

# FZF colors
export FZF_DEFAULT_OPTS="
    {0}
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="{{LS_COLORS}}:su=30;41:ow=30;42:st=30;44:"
"##,
        source,
        bg,
        fg,
        fg,
        palette[0],
        palette[1],
        palette[2],
        palette[3],
        palette[4],
        palette[5],
        palette[6],
        palette[7],
        palette[8],
        palette[9],
        palette[10],
        palette[11],
        palette[12],
        palette[13],
        palette[14],
        palette[15]
    );
    fs::write(dir.join("colors.sh"), sh).ok();
}

fn write_colors_css(source: &str, palette: &[String], bg: &str, fg: &str, dir: &PathBuf) {
    let css = format!(
        r#"/* CSS variables
   Generated by 'wal' */
:root {{
    --wallpaper: url("{}");

    /* Special */
    --background: {};
    --foreground: {};
    --cursor: {};

    /* Colors */
    --color0: {};
    --color1: {};
    --color2: {};
    --color3: {};
    --color4: {};
    --color5: {};
    --color6: {};
    --color7: {};
    --color8: {};
    --color9: {};
    --color10: {};
    --color11: {};
    --color12: {};
    --color13: {};
    --color14: {};
    --color15: {};
}}
"#,
        source,
        bg,
        fg,
        fg,
        palette[0],
        palette[1],
        palette[2],
        palette[3],
        palette[4],
        palette[5],
        palette[6],
        palette[7],
        palette[8],
        palette[9],
        palette[10],
        palette[11],
        palette[12],
        palette[13],
        palette[14],
        palette[15]
    );
    fs::write(dir.join("colors.css"), css).ok();
}

fn write_colors_scss(source: &str, palette: &[String], bg: &str, fg: &str, dir: &PathBuf) {
    let scss = format!(
        r#"// SCSS Variables
// Generated by 'wal'
$wallpaper: "{}";

// Special
$background: {};
$foreground: {};
$cursor: {};

// Colors
$color0: {};
$color1: {};
$color2: {};
$color3: {};
$color4: {};
$color5: {};
$color6: {};
$color7: {};
$color8: {};
$color9: {};
$color10: {};
$color11: {};
$color12: {};
$color13: {};
$color14: {};
$color15: {};
"#,
        source,
        bg,
        fg,
        fg,
        palette[0],
        palette[1],
        palette[2],
        palette[3],
        palette[4],
        palette[5],
        palette[6],
        palette[7],
        palette[8],
        palette[9],
        palette[10],
        palette[11],
        palette[12],
        palette[13],
        palette[14],
        palette[15]
    );
    fs::write(dir.join("colors.scss"), scss).ok();
}

pub fn invalidate(image_path: &str) {
    let key = cache_key(image_path);
    let dir = cache_dir().join(key);
    fs::remove_dir_all(&dir).ok();
}

pub fn get_cache_dir(image_path: &str) -> PathBuf {
    cache_dir().join(cache_key(image_path))
}
